---
title: Another Brick in The Wall - Part 2
author: TheDataAreClean
date: '2020-08-15'
slug: 2020-08-15-abitw-two
categories:
  - education
tags:
  - 100days
  - development
  - law and justice
  - abitw
  - musings
description: 'The Rights way..'
---

* __

# Flashback !
In yesterday's blog I tried to highlight the fact that the education system in India is a shit show. There is an immediate need for a larger understanding of the ecosystem to bring in any meaningful, sustainable change. With that in mind, today I am discussing one of the ideas currently in the research phase. The issue of **child rights** and it's connection to education.

# What ?
The objective is to better understand the issue of education through the lens of child rights implementation. Better understand the  fundamental rights of a child, how those right are implemented in the Indian law and justice context and how a child is protected and enabled through these systems.

# Why ?
One of the biggest challenges to solving education ecosystem problems is also visibility into what policies have been set to support a child and are they working as expected. If there is already a framework already in place, the challenge becomes easier to grasp in terms of what are the expectations and what the framework is achieving. And if there is an absence of framework, what changes need to be brought in to cover that particular area. This systems also highlights the gaps such that it becomes comparatively easier to attempt measuring the difference. Yep, that's the most confident I can be about that last statement in particular.

# How ?
How do we decide what is expected? Answering that would require a lot of back and forth and a lot of research into each and every thread, but there is one good place to start. The vision is to use UNICEF [Convention on the Rights of the Child](www.unicef.org/crc/) as the guiding principle for all child rights related interventions. Understand what each of the articles of the convention cover, are there any existing policies in India covering these and an analysis of the performance of those policies. One thing to note is that these policies will also lead to exploration of other sectors, like public finance if any monetary value release is attached to a policy, public health, ICTs, etc., etc. I would love to discuss these intersectionalities and their effects more, but maybe some other day.

# Plan .
For now the plan is to document these rights and understand which of these have a primary relationship with the education space. For eg. **Article 17: Access to Information** is pretty straightforward, but there could also be others which might not be connected directly but do influence the education ecosystem. This is not an easy one, I hope learn and unlearn a lot along the way. Until then..

**Note**: As I also mentioned yesterday, all the [research](https://github.com/TheDataAreClean/education) on this topic will be available in the open. You are welcome to use it, criticize it and contribute to it. Even the fundamental basis of this research.

PS. There is an excellent children's [picture book](https://storyweaver.org.in/stories/108374-i-know-my-rights) on the same topic published by the folks at my last organisation. I would strongly recommend checking it out.

**_TATA!_**

**_cube_**

[Part 1](https://thedataareclean.com/blog/2020-08-14-abitw-one/) & [Part 3](https://thedataareclean.com/blog/2020-08-16-abitw-three/) of the [series](https://thedataareclean.com/tags/abitw/).
