---
title: Order, Order
author: TheDataAreClean
date: '2020-08-28'
slug: 2020-08-28-order-order
categories:
  - me
tags:
  - 100days
  - organise
  - musings
description: "Spark Joy ?"
---

* __

I have a small confession to make. I absolutely didn't feel like writing today. I have been working on a [report](https://thedataareclean.com/blog/2020-08-27-step-zero/){target="_blank"} and for the last couple of weeks and writing the first draft and it's become a bit of an overload. I was struggling nailing down a topic for today and have started writing this at 22:31 HRS, by which time I am usually asleep, and I still don't have a clear idea on today's blog. Will probably make up shit as I go. A while ago I promised myself [100 days](https://thedataareclean.com/blog/2020-08-01-manifesto/){target="_blank"} of writing, day 28 will just have to be garbage.

I also realise that I am feeling a little sad today, which has been a constant underlying feeling for me lately. I was always an anxious kid, and thought of my shenanigans as just high energy crap. After a lot of introspection and professional help I realised the state of my anxiety and have since been learning to deal with it better.

Recently, along with all of the above, a new feeling has been emerging for me and this one has not been a great either. I have been experiencing this feeling of pointlessness in everything that happens around us. How the world is going to shits, my personal life is not going anywhere, no change in the world is permanent, society is a fucked up construct making everything worse, etc, etc. I am aware that things might not be all bad, I am just finding it hard to convince myself otherwise. Even with regards to my own work, feeling so passionately about education and trying to make the world a better place feels not enough.

I am tired of trying the same old ways to address this feeling. Spend money, feel better, avoid family, feel better, create schedule, feel better. It's just me going in circles for a while now rather that facing the feeling head on. So today is my public proclamation to try something different, to try and understand what I need rather than justifying or trying to find a solution instatnly. I will have to get a little uncomfortable before I get through this, and like my friend says, it build character.

**_TATA!_**

**_cube_**
