---
title: The Stress
author: TheDataAreClean
date: '2020-08-02'
slug: 2020-08-02-the-stress
categories:
  - writing
tags:
  - 100days
  - musings
description: 'Why did I think this was a good idea?'
---

* __

Yesterday, I took the "brave" step of publishing my [first ever blog](https://thedataareclean.com/blog/2020-08-01-manifesto/){target="_blank"}. It was mostly an announcement about of this journey I have embarked on. Somewhere in the mix was also this **GRAND** declaration of writing everyday for 100 days. 100 days of stuff which I feel is worth talking about. That's a lot of stuff, especially when I live alone, talk to just 3 people and have no clue how popular culture works.

# The easy bit
One thing surprised me a lot about the whole experience, how easily I was able to put all of it down on the paper (or [Markdown](https://en.wikipedia.org/wiki/Markdown){target="_blank"} file). Don't get me wrong, it's not like I am a natural, pro, type A individual who just makes things happen. Maybe because it was just an announcement and a few stupid jokes along the way, I managed. 

# The rush bit
At the end of the day I was filled with excitement and numerous brilliant (atleast in my head) ideas for things I want to talk about. Maybe I should make a list, maybe I should detail some of them, maybe I should write one in preparation for tomorrow!

# The feelings bit
How the education system in our country is a shit show, and the [NEP](https://www.livemint.com/education/news/mphil-to-be-discontinued-and-other-key-points-in-national-education-policy-11596022845294.html){target="_blank"} announcement this week. How [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software){target="_blank"} is amazing, yet so difficult to adopt in every aspect of life. How cycling is beautiful, therapeutic and so much more. 

Enter, anxiety. I am not really a education policy expert, I don't really use open source that much, I haven't really cycled for a while because of the pandemic.

# The stressful bit
There was this constant voice in my head, asking me to write something important, asking me to not waste other people's time. If I don't have something important to say, or add value to an already existing conversation of internet intellectuals, maybe I shouldn't speak at all. 

# The important bit
Thanks to a small interaction with my friend I remembered why I started this. Improving my writing, my confidence and not break the streak. I just need to start writing, something might come along.

So maybe that is what I will do going forward, talk about stuff that is present for me. If the world finds value in it, you are welcome! See you on the next one.

**_TATA!_**

**_cube_**
