---
title: The Productivity Tool Trap
author: TheDataAreClean
date: '2020-09-06'
slug: 2020-09-06-productivity-tool-trap
categories:
  - work
tags:
  - 100days
  - productivity
  - todo
  - organise
description: 'Which To-Do ?'
---

* __

I am obsessed with organisation. Day 2 of being back home, I was already cleaning up cupboards and organising my room. I love when everything is stored in a place made exactly for it. In short, I am insufferable. But leaving that part aside, I love doing the same thing for my work. Using productivity tools to meticulously document and arrange every last piece and then bask in the glory of perfection. Makes me happy just thinking about it.

In the attempt to optimize and perfect the whole process I keep trying out new productivity tools all the time. be it a to-do app, a task manager, a notes app, a combination of everything and more. You name it, I have tried it. I have gone through so many by now that frankly I have lost track. All in the search to find that one tool that will do everything you want, exactly you want it.

The cycle is pretty much the same every time. I am a few months into using one of these apps or tools, creating an intricate system of capturing notes, to-dos an reading lists in one homogeneous system when suddenly I hid a brick wall (actually a small bump) where I am not able to do that one particular customisation. One tiny thing in an otherwise well managed system, totally inconsequential in the larger scheme of things but it has ticked me off now. 

Thus begins the process of finding a new alternative, because compromise is not an option my ego allows. I have to go out looking for something new, something that fixes the current hiccup I am facing, if not fixing then giving me an entirely new workflow so I don't have to facing it again. And thus begins the trial and error process with most instances just being a case of money down the drain.

The countless times I have lived this cycle is equally exciting and exhausting. And for the the first time, because I am writing about it, I am wondering that is the problem with the tool or me? Do I tend to overcomplicate my setup by including everything is one app? Should I look for alternatives which specialise in individual formats and use them to their max potential? Maybe I just need to build my own mini workflow to manage everything the way I want it. But today I am trying a new app, moving all my stuff again, trying out a new workflow. This time it's open source!

**_TATA!_**

**_cube_**
