---
title: Competitive Streak
author: TheDataAreClean
date: '2020-09-10'
slug: 2020-09-10-competitive-streak
categories:
  - me
tags:
  - 100days
  - competition
  - ego
description: 'Ego fueled monkey brain..'
---

* __

I am an extremely competitive person. I will stress the fuck out when someone is better than me at the thing I care about, constantly wondering what can I do to get better. But I am not competitive in the way that I want to beat you, more like I want to reach where you are so I can have a great conversation with you. 

And I will work really hard to reach the point, a lot of times to my own detriment. I will take all the stress in the world and take it upon my ego to achieve something. Even if the end result ends up having no benefit to the entire process, I could've used that same energy to something more productive, something I care about. But no, I have to fuel my ego and achieve this inconsequential milestone.

The surprising bit is I was not always like this. I used to be the most lax person ever, never finishing anything or worrying about any consequences. I just wanted to relax all the time. I was so on the other extreme that there was multiple points in my life when I didn't care about my exams and almost suffered severly for it. I just couldn't be arsed to do anything. During once instance, my parents were so confident that I will not achieve a goal that the promised my a bike, and regretted it when they had to buy it for me.

When I went into my first job, something fundamentally changed about how I started approaching challenges. I just wanted to be a part everything, excel at everything and overextend to acheive all the targets, achievable or not. I try to think back to when did that start, was it the acceptance of my work, was it the compliments at work, was it some other deep shit which I have conveniently buried. Frankly I cannot point to the exact instance or moment, but I can clearly remember becoming a different person through my journey with my first job.

And many years later now, I am still the same person. Someone who is extremely competitive and takes it on their ego to achieve everything. And I wonder if I will ever take a break, or relax and be satisfied with my output. I wonder if I will ever just chill again.

**_TATA!_**

**_cube_**
