---
title: That Kind Of Day
author: TheDataAreClean
date: '2020-09-21'
slug: 2020-09-21-that-kind-of-day
categories:
  - me
tags:
  - 100days
  - musings
description: 'Is this allowed ?'
---

* __

**Day 52**.  

Today is probably my first unsuccessful attempt at writing a blog. I have been going through a lot of change recently, coming to Delhi, messed up sleep cycle, too much work and I miss my friends way too much. As much as I enjoy writing at the end of the day, the process has been counterproductive during the last few nights, I have produced some A1 quality garbage.

I sat down to write this blog and ended up watching to Queen live concert videos for the longest time, crying happy tears all along feeling much lighter at the end. The music is just beautiful and you can find the gem of the most amazing crown [here](https://youtu.be/ngf1KF2_kPI){target="_blank"}. And if you are not a Queen person, god forbid, you know what date it is today? [Do you remember](https://youtu.be/Gs069dndIYk){target="_blank"}? 

My ego is absolutely hurt, but I was physically incapable of writing today. I know I will regret it tomorrow and for the rest of my life. Tonight I have no choice but to take care of myself. Until next time !

**_TATA!_**

**_cube_**
