---
title: Aim High ! Go Low !
author: TheDataAreClean
date: '2020-09-20'
slug: 2020-09-20-high-low
categories:
  - education
tags:
  - 100days
  - r
description: 'Bare minimum explainer..'
---

* __

Like I mentioned in yesterday's [blog](https://thedataareclean.com/blog/2020-09-19-teach-learn/){target="_blank"}, I have been doing these weekly `R` sessions at my workplace and thoroughly enjoying them. And for these session, we decide to do some [#TidyTuesday](https://github.com/rfordatascience/tidytuesday){target="_blank"} challenges to learn together. Today's blog is about that, my journey to attempt the challenge, attempt a fancy blog around it, and then settling for what you are reading right now. Sorry about that! 

So it started with looking at the data, which to be fair is a brilliant one this week. It's public spending on kids by the US government. If it was India, it would have been the best thing ever. Since I am also working with public spending data and have enough work coming up the child education spending space, the dataset could not have come at a better time. Thus began my journey to do something exciting with the data. 

After a little exploration I found some pretty neat indicators around education spending and though about looking into that, created a complicated idea in my head and went for it. I wanted to check out the correlation between education and unemployment spending. I was creating this complicated chart which shows trends all across the map of the US, but then I realised how will I communicate all this to folks who are learning in these sessions. The most important thing is that I can show them new ideas around `R`. 

TI started modifyng my entire work into consumable `R` stuff so learning from the script happens smoothly. And this was the end [result](https://github.com/TheDataAreClean/tidytuesday/blob/master/2020/week-38/){target="_blank"}. Am I happy with it? Not really, I was aiming too high to be satisfied with this. But will it do the job tomorrow? Absolutely. I have done exactly the things I wanted to showcase and hopefully help folks learn along the way. 

One the data bit, I am just glad I got to play with this. It has given me so many new ideas, I want to see how many of these are possibly in my use case. This reminds me, [Central Square Foundation](https://centralsquarefoundation.org/){target="_blank"} has come out with this [School Eucation in India](https://centralsquarefoundation.org/school-education-in-india-data-trends-and-policies-eng-2020/index.html){target="_blank"} report, it has a lot of good data references. Do check it out if this kind of thing interests you. 

**_TATA!_**

**_cube_**
