---
title: Travelogue - Part 4
author: TheDataAreClean
date: '2020-09-30'
slug: 2020-09-30-travelogue-three
categories:
  - travel
tags:
  - 100days
  - travelogue
  - family
description: 'One of those days..'
---

* __

Have you ever been so blank that you thought of writing about an interesting conversation your parents but can't think of anything to share? 

Have you ever been so blank that you that you are exhausted out of you mind but can't even think about sleeping?

Have you ever been so blank that you are hurt but don't know how to fix it or if you even want to fix it?

Have you ever been so blank that you watch Naruto for two hours just to get over the exhaustion and sit down writing?

Have you ever been so blank that you can't write even after the break and put together a random blog just to get done with day?

Have you ever been so blank that you can't even be annoyed at the fact that you decided to write for 100 days straight.

Today is one of those days. Good night.

**_TATA!_**

**_cube_**

**PS.** This post is part of a series of post on my visit back home. You can find all of them [here](https://thedataareclean.com/tags/travelogue/){target="_blank"}.
