---
title: Setting Boundaries
author: TheDataAreClean
date: '2020-09-23'
slug: 2020-09-23-boundaries
categories:
  - work
tags:
  - 100days
  - boundaries
description: 'Where does one stop ?'
---

* __

I have had a funny history with jobs. I always join a place excited about the idea and the promise of the challenge, but soon get disillusioned by the reality of working at any institution. Sooner or later, the sheen wears off and you are left with the reality that you will need to move on to grow. Is the institute at fault? A lot of times, yes. But if you look a little deeper, all institutions are flawed by nature, even one where the people running that institute are good people. An institute will always be tied to the principles of capitalism even when the individuals hold themselves to better standards. Because that's what fuels our society, and there is no support for alternatives.

But today's post is not about any of that. I would love to talk about it, but it's a heavy topic for me to articulate this late into the night. Maybe another blog. Today I want to discuss setting boundaries for yourself while interacting with any workplace. Then why did I start with that other thing? I hope to bring it back to that point by then end. And if I can't, I will just blame my inadequate writing skills. 

So, back to boundaries. When I started working at my first place, I had absolutely no boundaries, none. I was working 16 hours a day, spending multiple days in office at a stretch and working like crazy man. I got so frustrated that I rage quit weeks before a promotion. But I don't regret any of it, and when I went onto my next job I was pretty clear on what my boundaries are. I had suffered enough in my first job to not make that mistake again. What also helped was that the neither the work, not the vision turned out to be too exciting for me to care enough. All of this led to my third stint, doing exactly what I wanted to do, doing it at a place I want to, doing it the way I want to. I hit the golden trifecta of a dream job.

And now I am struggling again. When I was at a boring job, I used to find time and do the exciting things I care about. Now when I am engaging with that work 4 days a week I am struggling to find when to stop. When to stop engaging, when to stop doing, when to stop thinking about it? Because no matter how much I love the work, it's impossible to engage with it all the time. I believe in the need to take breaks and come back fresh to that thing you want to do with more strength and will. One small break just makes you want to do something even more than constantly continuing without one.

And there is where I hope the point I am trying to get across makes sense. All the people in the organisation have constantly supported me to take my breaks and come back to work fresh as much as they can. While they have respected my space, all of us work in an environment where everyone cares too much and goes above and beyond. That is the tricky bit, did people support my choices but the organisation subconciously expects more? How can it be differnt, don't people make organisations happen? Does the organisations involvement in a capitalist structure hinder its values? Is all of this just in my head and maybe it's me who feels anxious all the time to overdeliver, feeling whatever I do is not enough. Mabye that's the centre of all of this. I hope to find out one day.

**_TATA!_**

**_cube_**
