---
title: ' Crossroads'
author: TheDataAreClean
date: '2020-09-04'
slug: 2020-09-04-crossroads
categories:
  - writing
tags:
  - 100days
  - musings
  - learn
description: 'Too much writing ?'
---

* __

I had been sitting for over 30 minutes, pondering what do I write about today. I had a fairly exhausting day and am travelling this weekend, both keeping my mind fairly occupied. I am also sitting with this feeling of being annoyed and thinking, I still have to finish writing bedfore I end my day. Noticing my annoyance I wonder, was [committing](https://thedataareclean.com/blog/2020-08-01-manifesto/){target="_blank"} to 100 days of writing a good idea.

I started this journey with the [objective](https://thedataareclean.com/blog/2020-08-02-the-stress/){target="_blank"} of getting over the fear of writing and hopefully also improving my skills along the way. I believe I have made great progress towards those goals. Even when I was working on a report for my office work, I was not as uncomfortable with the idea of writing as I usually am. 

Even after these considerable development in my experiences with writing, I am feeling this weight of writing everyday. The weight of thinking about a bajillion things before nailing down a topic, the weight of extending my days just to find some time to write at the end of the day, the weight of having something to say everyday. Some days I don't want do any of this, I just want to sit and stop my brain from processing every bit of information. 

I am also feeling that I am over sharing, by my standards, to just fill up blogs with content. I am not sure how comfortable I am with that but it's been in my awareness. But the thing I am probably most annoyed about is that I have not been able to read as consistenly as I usually do, be it newsletters, articles, books. It feels like I have stopped learning and thinking new thoughts, just relying on random tweets and conversations for content. I would love to put a little more thought and intentionn into my everyday writing.

As I am finishing today's blog, I am left thinking what do I tomorrow. Should I continue writing till I hit 100, should I take a small one day break, should I just move to a bi-weekly or something similar model. Maybe I am just tired today and tomorrow I will not feel the same and want to write again. I don't know what it will be, but I am glad I have the privilege to make such a decision around writing. See you tomorrow! Maybe.

**_TATA!_**

**_cube_**
