---
title: My struggles with FOSS
author: TheDataAreClean
date: '2020-08-03'
slug: 2020-08-03-foss-struggles
categories: 
  - technology
tags:
  - 100days
  - foss
description: 'Maybe I am a FOSS-il? Sorry.'
---

* __

# I love technology
I absolutely love it! The joy of possessing a new gadget, trying out a new app, figuring out how pieces of technology operate and customise them exactly to meet my needs. The better something is made, the more there is opportunity to mould it, I am sold! Take my money, please make my life better.

# What is all the FOSS about?
On top of all the gifts (and problems) technology has given to this world, probably the absolute best thing in my opinion is the [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software){target="_blank"} ecosystem. For the uninitiated, Free and Open Source Software (FOSS) has one main characteristic you need to know to understand and care about it. Anyone is freely licensed to use, copy, study, and change the software in any way. The source code is openly available and the community is encouraged to voluntarily improve the design of the software. How fucking amazing is that! 

Another thing that's great about FOSS are the values behind it. The term "free software" does not refer to the monetary cost of the software at all, but rather whether the license maintains the software user's civil liberties ("free" as in "free speech" not as in "free beer"). How can someone not get behind that?

# I am also a consumer
I am not a computer engineer, I am not even a developer. I am a statistician who codes a little bit on the side because I love to see how you can find beautiful things in everyday data if you wrangle it **just enough**. Most importantly I am consumer, who cares about and believes in the philosophies of FOSS but at the same doesn't understand the technology well enough to completely adopt it in my life.

# The commodity of time
I wish I understood more, I wish I could code better, build and own every piece of technology I use. Because that feeling is brilliant; that sense of freedom, autonomy and ownership when you build something on your own is unparalleled in any other technology interaction. When I built this portfolio using an open source framework and theme making my tiny customisations along the way, brilliant! 

But you know what else is brilliant, productivity apps. I absolutely love them and my favorite app ever is proprietary and free; the free as in "free beer" version. I really wish there was something like that in the FOSS universe. But for now there isn't, and I wouldn't mind capitalism fighting over a beautiful productivity app that gives me the near perfect experience I am looking for. It's just easy, and a lot of time it's hard to argue with easy. How do you find the time to learn a completely new skill and build something perfect for yourself, as much as I want to, when you have something easy?

# The hope 
I wish for something new to come along and elevate the entire process. Something for people like me who value the movement but also prefer the ease. A world where solutions to build and maintain software are distributed in similarly refined packaged systems like the end product itself. But it hasn't happened yet and maybe I am also a part of that problem. For now though, I will be taking small steps, keeping it easy.

**_TATA!_**

**_cube_**