---
title: Work Plan
author: TheDataAreClean
date: '2020-09-14'
slug: 2020-09-14-work-plan
categories:
  - work
tags:
  - 100days
  - musings
description: ''
---

* __

I recently noticed a pattern in my daily blogs, specially the ones which are more personal. I start by telling something about myself, my habits, my way of being, or something else. I follow it up by contradicting myself literally in the next fucking statement. I am still not clear how I always end up doing that. Maybe it's growth in certain aspects of life, maybe I a don't know anything about myself at all. Based on my experience, it's probably the latter.

Today's blog is an attempt to decipher one of those things I think I know about myself. Trying to understand where do I belong and most importantly deal with my own complex feelings. This blog is only going to end one of two ways; either I convince myself of the type of person I am or stress the fuck out and leave that problem to therapy. And during the course of this blog I might make a few statements claiming to be some random knowledge about myself. I would advise you to take all of it with a pinch (fistful) of salt.

For a long time I haven't had a clue about the kind of employment I want to have. Just to clarify, even though it's written in plain English I will explain it to you, I am not taking about career or job prospects. I am more talking about who do I want to work for and more importantly what do I want to work for. I am fairly principled person, I have very strong views on the idea of a good society which span across all kinds of environment I interact with. Since a big chunk of our lives are spent at work, it's important to do what you love and more importantly what you can tolerate. 

My principles also make a fairly opinionated person. I will make sure my feelings on the place I work are communicated, if I am happy about it or not. I also join workplaces with a high bar on the standard of work and more importantly culture of a place. I build expectations which are not always met. And sometimes I wonder, was the place I worked at problematic or my bar is too high.

If it's me, than the answer is pretty simple. I just have to accept that reality and find a way to work and sustain myself independently. Which also is my current life plan, not running behind a job. It's it the place, I wonder what kind of a workplace will satisfy me. The whole second side also makes me think, maybe it's just me. And like a mentioned earlier, based on my experience, it's probably the latter.

**_TATA!_**

**_cube_**

**PS.** Apologies if today's blog didn't make a lot of sense. It was written by a very sleepy me.
