---
title: Natural Disasters
author: TheDataAreClean
date: '2020-09-25'
slug: 2020-09-25-natural-disasters
categories:
  - mental health
tags:
  - 100days
  - ego
  - work
description: 'What is enough ?'
---

* __

Today marks the third day of my complex feelings around work and culture. I feel like I have landed on something here, even if it's just a bunch of feelings with no end in sight. And like the other two days, today I am attempting to make sense of all my feelings again. Mostly to go to sleep, leaving all the anxiety on this blog.

One thing to know about me is that I am an overenthusiastic cutlet. I like knowing everything, being involved in everything, participating in all conversations. If I am a part of the exercise, I am completely in. I will not sit on the sidelines and enjoy, if that's my role I usually end up leaving that task. 

The challenge with this entire setup is that it's extremely exhausting. When the work ends I am completely drained. But I would lie if I say that I don't enjoy it. But I also want a break. Yep I know it doesn't make sense, please bear with me. I just wish I cared a little less about some things, a little less involved, a little less anal about things, a little less pain in my own ass. 

A lot of my anxiety also stems from the feeling that I am not enough, what I am contributing is not valuable enough. I try to overcompensate by doing more, involving myself more and then hating every second of it. There is this brilliant comic by the brilliant [Sarah Andersen](https://sarahcandersen.com/){target="_blank"} (who is the most amazing ever), that [perfectly summarizes how I feel](https://www.pinterest.co.uk/pin/524247212877389674/){target="_blank"}. And I don't want to feel that way, sometimes I want to forget things and relax.

So that's where I am in life constantly, and one day I get tired of this shit and move on to a new place. A new place where I can convince myself of the same anxieties and start again. I don't want to do that all the time, I want to stick around and grow and evolve with a place and not hyper speed my way through it. Let's hope that day comes soon.

**_TATA!_**

**_cube_**
