---
title: Creating Organisations
author: TheDataAreClean
date: '2020-09-24'
slug: 2020-09-24-creating-orgs
categories:
  - work
tags:
  - 100days
  - organisations
description: 'Defeating the system..'
---

* __

**PSA** - Today's blog is a lot of feelings. Apologies if it doesn't make any sense.

In yesterday's [blog](lhttps://thedataareclean.com/blog/2020-09-23-boundaries/){target="_blank"} I briefly touched upon the fundamental flaw of any institution in a capitalistic structure. No matter how hard you try to stick to your principles, working in a society that incentivizes constant production over mindful interactions is always a challenge.

What I am not doing today is discussing how to build an organisation without compromising on an individuals or principles, I have absolutely no experience in that area. I am more interested in discussing the same from the lens of an empathetic contributor to the organisation. Because I am involved in similar situations right now, and I love the people and the cause I am working towards. What I am struggling with is that the structures we reside in is taking over that one beautiful thing too.

Let's start at the fundamentals. Any individual or organisation engaging with the market to move towards their mission, be it profit making or world peace, is engaging with the same capitalist structures and in a way supporting them. That includes all of us, that also includes me. Because all the interaction we have are dependent on outputs, you have to produce to survive in the system. And I empathise with the organisation I am working, because as brilliant as everyone there is as individuals the survival of the collective depends on the participation in the system. And it's nearly impossible to break from the system, you have to engage with it to change it.

That leads me to the second part of the challenge. How does one stand by their principles, while also engage with the system? How does one do tha while also empowering everyone around them to be their true selves and not succumb to the system. At what level, the individuals making the organisation start harming the individuals and how do we stop it? 

How to create a collaborative system of ownership and responsibilities while empowering everyone eveyone involved and not let them feel brought down by the ways of the system. Because the system was not created keeping everyone in mind, we shouldn't try to force fit everyone in it. I was discussing the same today with a friend and we came to the following metaphor. If you went on a road trip with your friends, all of you take turns driving, and if someone can't drive they are usually in-charge of something else. Everyone has a responsibility to ensure a fun trip. How do we emulate that in an organisation without constantly demanding something.

**_TATA!_**

**_cube_**
