---
title: Inspiración
author: TheDataAreClean
date: '2020-08-18'
slug: 2020-08-18-inspiracion
categories:
  - me
tags:
  - 100days
  - musings
description: '< Insert Inspirational Quote >'
---

* __

# Not a Ted Talk
I am going to start today's blog with a random question. What inspires someone? Don't worry, this is not one of those self help blogs, I am just curious. Also I was struggling with topics to write about, happens when you are doing it for 18th day in a row

But getting back to the point, what keeps you ticking? Is it support of friends and family? A larger cause you believe in? Any deep-rooted anxiety that makes you feel you will never be enough no matter hard you try and your life is a failure? Asking for a friend.

# All the things
I have found inspiration in the randomest of places. Disclaimer, I am also a fairly emotional person so doesn't take a lot. A video on the internet about a dog who walked after years of perseverance? I am sold! A tweet by a random individual supporting and loving people on the internet? Going one, going twice, sold to the gentleman with a box of tissues wiping his tears! But by far, the most inspirational content ever put up on the beautiful universe that is the internet is live performance videos on talent shows. The number of times I have watched [Got Talent](https://en.wikipedia.org/wiki/Got_Talent){target="_blank"} singers late at night on YouTube to feel less depressed is way too many. It's amazing to see people come from different backgrounds all around the world singing their hearts out and getting that [Golden Buzzer](https://youtu.be/cf8zxj7n1cs){target="_blank"}. I am pretty sure that production plays a big role, but I don't care. That shit is inspirational as fuck!

# Ego
One more thing which I believe is important to mention here is I have a am extremely competitive. My ego just doesn't let live with the fact that someone knows more than me on that one topic I care about. I know, I know, there will always be someone who knows more and that this is an extremely unhealthy never ending cycle with it's roots capitalistic brainwashing. But in my defence, I am competitive not in a way where you bring people down so you can pull yourself up, but more in the way of finding someone so inspirational that I want to talk to them and learn from them about the same things you care for.

# People
That brings me to the thing that inspires me the most. People. As much as I dislike humankind, there is something about certain individuals. Think of that one beautiful conversation you had with your friend about the world that you regularly recall. Or that one person you know who wholly commit to the something they believe in. Just people bringing 100% of their selves in the moment. That's what I find most inspiring the most. I hope to inspire people like that one day too.

**PS.**: Just wanted to point out, there is nothing wrong with self-help literature. If someone finds value in things you and I don't understand, we are no one to judge. That, was my TED talk.

**_TATA!_**

**_cube_**
