---
title: Note to Self
author: TheDataAreClean
date: '2020-08-08'
slug: 2020-08-08-note-to-self
categories:
  - writing
tags:
  - 100days
  - learn
  - musings
description: 'Overanalyse everything !'
---

* __

If you have come here for the first time, welcome! It's mostly me talking about my feelings and other shit. And if you have been here before, you know the drill. Nothing beyond this statement is going to make any sense. 

So if you have been here before you might also know that last week I made a [commitment](https://thedataareclean.com/blog/2020-08-01-manifesto/){target="_blank"} to write for 100 days straight to get over my fear of writing and improve my skills along the way. It's been going pretty well till now, I wrote for seven days straight! Something I would've never imagined myself doing, forget enjoying it. I also ended up writing a couple of blogs I am really proud of ([here](https://thedataareclean.com/blog/2020-08-05-data-suite/){target="_blank"} and [here](https://thedataareclean.com/blog/2020-08-07-saving-private-data/){target="_blank"}). 

I was looking back at the week and thinking about it how it went, am I a fraud, does the internet hate me already? You know, the usual. But one thing in particular I have been thinking about since morning is about my writing style and the room (more like a mansion) for improvement. 

I had been using this style of section headers and a dump of thoughts, it helped me structure my thoughts better and also worry less about narrative coherence. I don't know if I want to continue with it or change it up. Today is an attempt in a different direction. Let me know if it's working or not.

I have also been contemplating writing about heavier topics, a lot of it stemming from my research work. But with the goal of writing everyday and a time limit on the effort I am parking that I idea for a bit. It might require too much research and more to put each blog together, maybe 92 more days later. I realise a lot of times I am thinking in bullet points. Which is an extension of the section thing, and also my need to compartmentalise and organise stuff to make sense of it.

This week also made me realise a few things about my process. How I am more attentive through the day, in some way also thinking of stuff I can write about. I like writing at the end of the day, it takes the stress away. I am more open to talking about my thoughts on the internet, than in person. When I am out of ideas I just go on Twitter till something clicks and like every internet intellectual I pretend I have something important to say about it. Also most importantly, I love cracking stupid jokes and the more I can fit into my writing the better I feel about it.

Parallelly, I am also trying to make a few tweaks to the website to make the experience a little better. If you notice anything that you would like to be fixed or appreciate taken care of, let me know. I have put considerable effort in getting this up even through my struggles with [FOSS](https://thedataareclean.com/blog/2020-08-03-foss-struggles/). Looking at me quoting myself four times in one blog. One week and it's already downhill, time to stop for the day. See you beyond the edge.

**_TATA!_**

**_cube_**