---
title: Death
author: TheDataAreClean
date: '2020-08-24'
slug: 2020-08-24-death
categories:
  - me
tags:
  - 100days
  - death
  - musings
description: 'Part of life.'
---

* __

I want to talk about a topic that has fascinated me for as long as I can remember. I don't remember how young was I when I first understood it's meaning, but I remember thinking: "Sure, this makes sense.". And something else that fascinated me was how much everyone hypes it up. I am talking about death. Yep, today I will be discussing the D word and related things. If this is not your cup of tea (or goblet of blood), please feel free to skip this one. There might be a lot more of me sprinkled all over the blog.

I have never really understood the importance death receives, along with the caution people exercise while discussing it. Sure it sucks and folks are missed when they pass away, but mostly it's par for the course. I often say this to my friends: "Death is the only thing we all have in common.". Also, I believe right now is good time to clarify, I don't want to die or anything like that. I am pretty happy with my life and would love to keep living it, for now. I just don't feel as strongly about death as a lot of people I know do. I will not be too bothered if it doesn't work out tomorrow.

I understand this might be make you feel uncomfortable, it's making me uncomfortable too. Maybe because we don't talk about it enough and respect it as a part of our realities. I hope today is one step in that direction.

Moving on! I admit dying pretty much sucks, no arguing that one. But I also believe it mostly sucks for the people left behind. Because the ones who have left got the good part of the deal. No more struggling with daily life, figuring out more shit, worrying about the world going to shits. Who wouldn't like that deal.

Having said that, I do still wonder why we hold death in such regard. Maybe because we are inherently selfish beings? Selfish about our own lives, self about other lives around us. Maybe it's the fear of the unkNown? Driving us more and more to avoid death, atleast a painful one. Maybe I am scared of death too? And this blog is my way of convincing myself otherwise. Maybe It's Maybelline.

So that's where I am today. A bunch of convoluted thoughts around a tricky topic, trying not to upset anyone along the way. So unlike me. I was almost considered not posting this one.

**PS.**  Today's post might read a little (a lot) ignorant and incendiary but that was not the intention. I was also trying really hard to be politer than my usual self. Do let me know if any of this didn't sit well with you.

**_TATA!_**

**_cube_**