---
title: Hype Machine Learning
author: TheDataAreClean
date: '2020-09-22'
slug: 2020-09-22-hype-ml
categories:
  - technology
tags:
  - 100days
  - ai
  - ml
description: 'Will you learn from the machines ?'
---

* __

Do you know about machine learning? Do you know about artificial intelligence? Do you know that it's the greatest thing that has ever happened in the history of the universe? Do you know data is the new oil? Are you loosing out on the discovery of the century? Do you want to know the secret? Don't you need to succeed in your business? How can you have a business that thinks rationally and doesn't fall for this bullshit?

Are you learning the latest skills to advance your career? Are you learning to build models? Can you predict the random inconsequential problem? Can you run a NLP algorithm? Can you create a decision tree? Is your xG boosting well enough? Are you doing data science? Do you know analytics? Are you paying obnoxious amount of money to learn a something that's available for free and still don't know anything?

Don't you know everything in the world needs artificial intelligence? Don't you know we will sell you solutions to the problems we created through capitalism by selling you meaningless solutions? Don't you know nobody wants to solve the real work problems and just throw money at the next exciting thing? And finally, don't you know that even machines learn when you feed them the same garbage every time?

**_TATA!_**

**_cube_**
