---
title: New Cube Policy
author: TheDataAreClean
date: '2020-08-26'
slug: 2020-08-26-my-policy
categories:
  - mental health
tags:
  - 100days
  - family
  - home
  - musings
description: 'Researching your own life..'
---

* __

# Struggle
As I [mentioned](https://thedataareclean.com/blog/2020-08-23-bangalore-diaries/){target="_blank"} few days ago, I am planning to go back to Delhi for a bit. Just see the family, hopefully relax a little and come back fresh. One thing I didn't mention is how I am mostly doing this against my will. My family had been raising the point of me visiting for a while, and the pandemic was (still is) making it difficult to travel so I just kept pushing it. Also frankly I didn't want to go back, my parents and I don't really have the most stable relationship to put it mildly. Now that I have booked my tickets, I am freaking the fuck out. Everything from, what if I am asymptomatic and take the virus to my parents to how will we mange a month without conflict to will I be able to continue writing daily.

# Reason
I have been constantly having these arguments in my head about whether I should just cancel my trip back home, for reals. There are these two voices in my head, constantly arguing the pros and cons of either possibility. And I have been wondering if the collective good of making this trip is worth the collective harm? The thing that worries me most how all of it will affect my mental health and can I take that blow.

# Treason
The challenge with that entire setup that's playing in my head was that it was an argument, I never really stopped and tried to have a discussion. There was no hearing and accepting different realities, just points and counter points. Rather that stating why I should do something, it mostly becomes why I should not do the other one. If I don't go my parents will do emotional drama, if I go I will have to sacrifice my person schedule, and on, and on.

# Protection
What I was failing to recognise was that both these voices were coming from a place of self protection. One trying to protect me from my family drama, the other trying to also protect me from family drama. There is no escaping the drama in a Punjabi family, that's our oxygen. And it became more and more important to hear both of them out so that I can talk to my parents about it. About why I feel, whatever I feel, about coming back home right now.

# Research
While I was going through this realisation, a fascinating thought hit me. At work I put in so much hard work to ensure that I do all the research, know all the important stuff and ensure I am well aware of the space before we take any action or make any recommendation. And here I am, ignoring all of it when it comes to my personal life. I was following no policy or framework to even try to understand what I want, I was just reacting to the situation. And all of us know very well how decisions taken as a reaction to some event never really work out in the long run. I don't know if I will go home or not. frankly I am not that bothered right at this moment. I will make that decision when the time comes. What I am excited to know is where this new found awareness takes me.

**_TATA!_**

**_cube_**
