---
title: Pillar No. 4
author: TheDataAreClean
date: '2020-08-30'
slug: 2020-08-30-pillar-four
categories:
  - media
tags:
  - 100days
  - musings
  - social
description: 'Where the money flows.'
---

* __

I have been thinking of quitting Twitter for a while, it's one of the only remaining social media platforms I am still using. The other is Reddit, that shit is too sacred. But the thought of deleting my Twitter account has crossed my mind a few times, the negativity that platform radiates is at another level. But that is not what today's post is about. It's more about information and the role Twitter is playing in it.

The reason I joined and stuck with Twitter in the first place was that I am an information junkie. I always want to know what's happening with the stuff I care about, and I want to know it immediately. And the ferocious pace at which you get information on Twitter is amazing. Today Twitter has also become the primary medium of communication for the news media ecosystem which is not their own platform. The biggest politicians, voices and media houses around the world use Twitter as their main arm of direct communication with the public. It has essentially become and extension of the 4th pillar of our democracy, just like Hrithik Roshan's 6th finger, but in the worst way possible. 

The news media ecosystem was already pretty to begin with. Problems like the slow suffocation of local media, the bias in covering marginalised communities and the broken business models have existed for a while now. The rise of digital news media solved some of the issues by democratising the voices and access to the information, but the problem of sustaining the developed ecosystem never went away. 

The biggest challenge the news media faces is sustainable business models. A majority of the places run on advertising, the big front page ad, the annoying pop-ups on websites, the permanent advertisement graphics on TV news. All these ads, being shoved in your is the money that's paying for these business to run. For businesses to earn more money, more people have to consume through their medium leading to more people looking at these ads. The best way that can be done is through sensationalisation, click bait and extreme statements. And the reality is, in a world with limited attention spans this technique works pretty well too.

Reporting, research and analysis have become a fool's errand. These activities take time and money, and do not give enough eyeballs in return. On the other hand a spicy, reactive headline inciting unwarranted action do just the job and require little to no effort. And now social media has become such a big piece in the puzzle, we see the same realities extending there. Some media house shitposts something completely obnoxious and the entire platform goes into attacking or defending that one thing, continuing the cycle and increasing the amount of shit. And the people who benefit are the organisations that posted this crap, because they got the eyeballs. At the end of the day, that was their only goal and they succeeded. The entire cycle does is it incentivizes lazy journalism, because the goal posts are different.

Another big problem the advertising business model has it that it curbs the freedom of the reporters. Majority of advertising money comes from big companies and government, giving them control over what kind of information goes out, more importantly what information doesn't. Why will any news media organisation ever want to hurt their paycheck. The whole system creates a cycle that harms the flow of information important for a healthy democracy.

The only way to get out of this cycle is to break it. Paying for the news, supporting independent journalism become critical in getting people's voice to the forefront rather than government and advertisers. Find your favourite media outlet and support them, to keep the information free.  

**_TATA!_**

**_cube_**
