---
title: Travelogue - Part 2
author: TheDataAreClean
date: '2020-09-09'
slug: 2020-09-09-travelogue-two
categories:
  - travel
tags:
  - 100days
  - travelogue
  - family
  - politics
description: 'Broken news..'
---

* __

One of the biggest grinds I have with living at home is my parents watch a lot of television. Nothing wrong with that, please go ahead watch as much as you like, enjoy the fuck out of it. But at our home, family time is television time. That means you have to sit with them while they also simultaneously entertain themselves with objectionable garbage. 

I on the other hand absolutely despise television, specially the ones that are turned on. Too much noise and brightness for no absolute reason. Damn I sound like such an old man shouting at the sky. But yeah, living alone in peace away from all this had decreased my tolerance level even more. 

All the things my parents watch primarily falls into two big buckets, daily soap dramas or daily news channels. Even though it's hard to tell the difference these days. I am okay with the crazy soaps they watch, as incredibly problematic they are, they are still the primary source of their entertainment. It's like I wouldn't want want my parents to constantly judge me for watching some anime. They don't understand it, but they can live with it. All I can do is reciprocate.

It's the other bit that drives me up the wall. It's the so called "news" channels, spewing garbage every second of everyday with absolutely no sign of research or even reporting. I constantly worry that these channels is the primary medium through which my parents create their world view. And exchange the same baseless arguments when discussing a topic with anyone. There is no effort in any corner of these so called news channels to ensure factual reporting, or holding the powerful accountable.

The television news ecosystem is broken to the core. The revenue model of the entire setup is advertising, and the point of having viewers is to have eyeballs, not to inform. As long as you are watching, the news channels are getting paid. If you want news that speaks for you, you will have to pay for it instead of the advertisers. If you want entertainment, I guess you are more than sorted. 

**_TATA!_**

**_cube_**

**PS.** This post is part of a series of post on my visit back home. You can find all of them [here](https://thedataareclean.com/tags/travelogue/){target="_blank"}.

**PPS.** On a completely different note, I am thinking of trying a [new design](https://tdac.netlify.app/){target="_blank"} for my website. Something a little more simple and clean. Would love any feedback, reactions, suggestions. Thank you!
