---
title: The Good Things
author: TheDataAreClean
date: '2020-09-02'
slug: 2020-09-02-the-good-things
categories:
  - me
tags:
  - 100days
  - family
  - home
description: 'There must be some pros to this.'
---

* __

# Incoming
I am travelling to Delhi this weekend, and plan to stay there with my family for a bit. And I have a [lot](https://thedataareclean.com/blog/2020-08-23-bangalore-diaries/){target="_blank"} of [feelings](https://thedataareclean.com/blog/2020-08-26-my-policy/){target="_blank"} about it. Feelings range on everything from excited to seeing Delhi again since January, to relaxing a little bit at home, to meeting my sister and so much more. 

# Sadness
But the feeling that is stronger than all the others is probably sadness. I have a very tricky relationship with my parents, we disagree on almost everything and find it difficult to communicate a lot of the times. My biggest concern is all of adjusting to each others lives after I have stayed away for so long. I wish it was easier but that doesn't seem to be the case.

# Sunshine
I was talking to a couple of my friends about this and both of them were trying to cheer me up about the entire thing and think about the things I want to do. That suggestion really clicked with me and I thought that's what I want to do. I thought it will be a good idea to list all the things I am looking forward to. And since I write I blog everyday, I thought what better place to list them down.

# List
So here it is, my list of things I am looking forward to when I go back to Delhi. In no particular order, who am I kidding, it's in a descending order. I will always rate and arrange things in order.  

**1.** I miss my sister. She is my favourite person in the world and I haven't seen her since January.  

**2.** Taking a break. Living alone is tiring and the pandemic doesn't help.  

**3.** Home made food !  My mom makes the amazing food ever and I miss onion paranthas.  

**4.** Cooking ! Since I have been living alone I have started enjoying this more and want to learn some family recipes.

**5.** Delhi again. I am always surprised by how much it has changed every time I go back.

**6.** Long lost friends. I only talk to them when I go back to Delhi every time.

And much more !

# Maybe
When I started writing down this list, I was surprised with the amount of stuff I am looking forward to. It fills me with a little hope that there is more to the entire visit than I was focusing on. I look forward to checking all these items. Like always, caution is recommended.

**_TATA!_**

**_cube_**
