---
title: The Balancing Act
author: TheDataAreClean
date: '2020-08-06'
slug: 2020-08-06-the-balancing-act
categories:
  - me
tags:
  - 100days
  - learn
description: 'When you want to learn everything..'
---

* __

**PSA**: I am too late to the writing party tonight. It's 2136 HRS at the time of me starting and I am fairly tired, might be pretty much garbage. Feel free to skip this one, but I shall persevere!

# Learn
I can't sit still, I am always doing something or going to do something. I am a restless being and mostly just stop when I go to sleep. It's not the best. As a result I am also obsessed with learning new shit, wanting to now how every small cog of any machine moves. Earlier it used to be wanting to learn everything about everything, but that grew tiring very quickly. Now I dive deeper and deeper into one topic and keep going down the rabbit hole with more questions and more ideas. It's just a never ending cycle, and frankly I love it. It tells me how little I will ever know about anything, keeps me grounded. 

# Core
I also love to learn because it gives me the opportunity use my skills to find a better way to do it. I am a statistician and a data guy at heart, everything comes back to that. I am passionate about education sector reform, not matter what I learn or research, I always ask myself the question, how data can be brought in to improve the discourse. The response is never straightforward, also it shouldn't be. Data is supposed to act as an enabler, never the answer to a problem. But that is a completely different conversation.

# Compete
A lot of times after my research, I go on to passionately argue my theory of change, with anyone who is willing to listen. Mostly to hear back how reasonable or stupid it sound and correct course. I often feel lucky after the discussions and the responses, how folks come up with new ideas and angles I didn't even consider. While I am in awe of their brilliance, I am also a fairly competitive person myself. Not the competition where I want to know more and beat you, but the competition where I want to learn more so that I can have another engaging discussion with you. A satisfying conversation, it's the best thing in the world!

# Worry
What also happens as a result of the conversation is that I worry. I worry that I don't know enough, that I am going about it the wrong way, that I will never be able to make any real change. Also impostor syndrome, if that even exists, I heard a great argument once that it doesn't. I will probably talk about it some other day. But the long and short of it is, as a part of the enriching conversation, self doubt tags along. And to overcome that doubt I try to learn everything about everything and stress myself out a lot more. But like I mentioned earlier, it's extremely tiring.

# Grow
In an attempt to measure my own expectations and also find better alternatives to this cycle, I tried asking two of my friends about this. Both of them fairly accomplished individuals I look up to gave me decent ideas to ponder upon. The general advice was that you find a balance between both worlds, you leverage your core but derive value from other sources wherever you can through careful engagement. The tricky bit is that it requires a little bit of patience and sitting still, hmmmmmmmmmmmmmmm.

**PS**: Reading the blog again before publishing made me realise how it sounds a little self-help-y. Nothing wrong with that, just not my thing. This was just meant as a dump of my feelings, but again you are welcome to find any value you can in this.

**_TATA!_**

**_cube_**