---
title: Reader's Indigestion
author: TheDataAreClean
date: '2020-08-13'
slug: 2020-08-13-reader-indigestion
categories:
  - read
tags:
  - 100days
  - learn
description: 'Padd lo beta, kaam aaega..'
---

* __

# Reading for God's sake
Greetings fellow reader! Yes you, you are a fellow reader! You are reading this, you can't take it back now! Welcome to the club! We will force you to enjoy it. Also, a small clarification on the section heading, there is no God. Breaking News! Sorry you had to find out like this. Unless you know someone named God. In that case, my God! 

But getting to the main point, reading is fucking mind blowing and probably on of the most fulfiling experiences of my life, yet. If you have anything to say against it, I would just like to point out that you are wrong.

# Reading for fun's sake
I became a reader pretty late in my life. It was my high school English literature books when I first time actually enjoyed reading. And I was 20 before I started reading just for the joy of it. Mine was not really a family of readers, initially my parents used to gasp in horror at the price of graphic novels and wonder why am I spending so much on books. But they got used to it, and my number of bookshelves started increasing.

# Reading for learning's sake
Soon I moved to reading more non-fiction, to then only reading non-fiction for a while. It is funny how you tell yourself that reading non-fiction gives you this moral high ground over other kinds of reading, yeah it's all bullshit. I realised after two years of doing just that, one day I was discussing my favourite books with someone and all of them up until then were fiction stories. Not even one non-fiction book on the list. That made me realise what I was missing and went back to it again. It has been one of the better decisions I have made in life.

# Reading for anxiety's sake
There was another moral high ground which I took with the whole reading thing. Reading over everything else! There is a movie about something? The book will be better. There is a podcast on an interesting topic? I rather read the article. There is a book about reading? Let's read that shit! You convince yourself that reading is the purest form of consuming any information, why ruin it? All this while the pile of things to read keeps increasing, giving you anxiety. And after a while you stop remembering most of what you have read because you never really paused to enjoy it. Sure too little reading is not fun, but too much is definitely not fun either!

# Reading for reading's sake
Since then I have tried to have a healthier relationship with reading. Like everything else in the world, it's only great when consumed in measured quantities. No more never ending reading lists, no more thinking about the next thing to read even before I finish the current one. And taking that break in the middle, thinking about what you just read and enjoying that shit. Just being with that one article, paper, book till the next one comes along. Happy Reading!

**_TATA!_**

**_cube_**