---
title: August Rush
author: TheDataAreClean
date: '2020-08-31'
slug: 2020-08-31-august-rush
categories:
  - writing
tags:
  - 100days
  - musings
description: 'Reflective material.'
---

* __

# Milestone
Today marks one month of me writing and publishing a new blog every day. It's been an insane experience and something I would've never imagined myself doing. As I am almost a third of the way into my journey of writing for [100 days](https://thedataareclean.com/blog/2020-08-01-manifesto/){target="_blank"}. I thought I will do one of those reflection blogs. Share my experience of setting up and writing this blog with everyone. Minimal effort, maximum feelings. Hope you enjoy it.

# Technology
First of all, the setup. I am an absolute tech noob and have no experience whatsoever in creating or hosting websites. When I started setting up my own website for the first time I had used Wix, which top be fair is pretty neat and powerful, I just never got comfortable with it. It  was a feature overkill, it wasn't open source and I really wanted to use the [R](https://cran.r-project.org/){target="_blank"} (a programming language I love) to build my website. I used the [Blogdown](https://github.com/rstudio/blogdown){target="_blank"} package in R to generate static websites based on [R Markdown](https://rmarkdown.rstudio.com) and [Hugo](https://gohugo.io). In short, the package took care of the design and the hosting, I just had to worry about the content (and my jokes). The design thing reminds me, I am thinking of changing my website design again. I am getting bored of the whole bootstrap thing and want to pick something absolutely plain and minimal so I just stick with it forever.

# Content
Writing overall has been amazing fun. Sure I have had bad days where I didn't want to write, or days where I have just written garbage I will probably never go back to, but overall I am pretty satisfied with how it went. I am also pleasantly surprised how comfortably I was able to transition into writing regularly, even if it wasn't anywhere near the best quality. The thing I am most happy about it that I am less scared to write on things I care about, I am more trusting of my research and my thought process. I know the next month will be incredibly difficult, but I am looking forward to writing more.

# Sharing
One thing about the whole writing journey that has surprised me the most is how I have started sharing a lot more with the world. I am a fairly private person and I don't like sharing a lot of information about myself anywhere. But with writing I just feel more comfortable talking about things I wouldn't in real life. Maybe it's the pressure of producing new content everyday or just the relief of being able to articulate my thoughts without the fear of being judged. I still don't know, but I want to keep going and find out one day.

# Introsepction
Lastly, I am thankful to writing. The whole process has changed the way I interact with the world around me. I am so much more attentive, mindful and welcoming of new thoughts and conversations. Even if it's not conversations I just feeling writing is becoming this session at the end of the day where I talk to myself and articulate what's present for me. Something I find difficult to do in my head because I am always fighting with my own thoughts. It's like giving myself the opportunity to be me. I am excited to find out what the remaining 69 days have in store for me. Nice.

**_TATA!_**

**_cube_**
