---
title: Finding Emo
author: TheDataAreClean
date: '2020-08-04'
slug: 2020-08-04-finding-emo
categories:
  - me
tags:
  - family
  - 100days
description: 'Step by step..'
---

* __

# Family matters
Often while talking to my friends about their childhood, the conversation steers into stories around family vacations, or family history. I am always left wondering why don't I have any such stories to tell. Did I not have lot of fun as a child in my family? Did I not enquire enough about my family history? Do I even feel connected with my family? If this went dark very quickly, apologies. This short tale that has a hopeful ending.

# Parampara, Pratishtha, Anushasan
I would start by mentioning right off the bat, my family is not that bad. For starters they are not evil, sure they are pretty orthodox, misguided by both their religion and the society, contributing to a slow and painful disintegration of all democratic institutions of the country. But if you can talk to them about it, a big if, and if they understand, even bigger if, they will feel guilty. Which is lot coming from them, trust me. Also important to mention is that they have supported me through a lot, especially when I was lost big time. Then why do I have this empty feeling, like something is missing, like I don't belong?

# My values
Admittedly, I have a very low tolerance for bullshit. That wasn't always the case, but things changed. And now if I get even a sniff of the bullshit I am done, and you will hear about it. And I believe that's the challenge; families, histories and traditions are just seeped in bullshit. You wake up to patriarchy, all the jokes are sexist and shit like casteism is a permanent resident of your house. It's a 2BHK with four adults, there is already a lack of space (physical and mental). Every morning, my bullshit meter used to start at 100 and it just never stopped.

# What a sucks
It sucks to not have many happy memories, to not fondly remember many family vacations or reminisce over family history. To feel this gap in your own story about your life. I wish that wasn't the case, I wish there was more. But I just didn't know how to do any of that when my bullshit meter was a fucking siren. How do I turn a blind eye to all of that just because they are my family and that is where I am supposed to "belong".

# Searching
One thing all of this made me realise that you will find your people. People who support you, believe in things you stand for and believe in a better vision for this world. You just have to keep searching and you will find the place where you belong. The road to that belonging might be pretty lonely, but you will get there. I found mine in my friends, my work and the [#rstats](https://twitter.com/search?q=%23rstats){target="_blank"} community. Till then, chakki peesing, and peesing..

**_TATA!_**

**_cube_**