---
title: Violent Streak
author: TheDataAreClean
date: '2020-09-11'
slug: 2020-09-11-violent-streak
categories:
  - me
tags:
  - 100days
  - anger
description: 'Perpetually angry brain..'
---

* __

I am an fairly (extremely) emotional person. A lot of my life till now, most of it, has been driven by strong emotional decisions. All the my successes, even more failures, friendships and more have had a heavy dose of emotion involved. I love it when good music makes me cry, I constant want to hug my friends, I even quit my job once weeks before a promotion. All because of, you guessed it, emotions!

One emotion that has gotten the better of me at multiple occasions is anger. It takes very little to make me angry, I just snap in a moment when I hear something that displeases me. Imagine a person's head from the movie Inside Out, but anger was the boss there and everyone just follows their lead. Since I am a fairly emotional and private person, a lot of the times I will bite my teeth to not display my anger, mostly unsuccessfully.

When I was younger, my anger was in a worse place than it is right now. I used to go red and instantly shout back, there were instances where I have angrily punched the wall and ended up regretting it. Over the years I have learned to measure my response and consequently my anger to any situation. Now I just punch furiously in the air till the anger dies down.

I am not for one moment claiming any emotion, specially anger, is bad. I think of emotions as a superpower, an integral component in every aspect of life. Every decision involves emotions at some level, it just might not be as strongly occurring as in my case. There is also the negative connotation attached with anger, that if you are getting angry then you are weakening your stand. I don't think I believe that, sometimes you just need to be angry and let everyone know that you are angry. There is a larger thread also at play here that the capitalistic environment we live in doesn't really support for emotions. Emotions are not effective or mainly efficient enough a medium to get through some tasks when the primary objective of the system is creating outputs.

Even after all of that, I do believe that there is space for me to temper my emotions. Not that I want to, but to have any constructive conversation around something you care for becomes a challenging task if you are not measured in your response. So nowadays I try to step back for a second and evaluate my response. If I find myself getting angry I just try to breathe through it, it's mostly better than the Hulk smash alternative.

**_TATA!_**

**_cube_**
