---
title: Boss Kapital
author: TheDataAreClean
date: '2020-09-15'
slug: 2020-09-15-boss-kapital
categories:
  - capitalism
tags:
  - 100days
  - musings
description: 'The clow..'
---

* __

It's only Tuesday and I have already had a fairly exhausting week. I had a plan to write my blog a little early today and go to bed on time, something I haven't been able to do for the past week. But then I was reminded, by the beautiful Twitter, that there is an [Apple Event](https://www.apple.com/apple-events/september-2020/){target="_blank"} today. There went my entire plan, and I am writing this blog at 11:30 in the night. This might be a short blog (rant) today.

I would say, I have more than enough adopted the Apple ecosystem or products (not services, yet) to care about the event. Over the last few years I have happily enjoyed the comfort an interoperability of their devices, while my tech noob tech brain didn't have to worry about stuff beyond my work on the devices. I gleefully watched the event and enjoyed the new generation of products and secretly wanting to own them. There was a time I owned a lot more apple devices than I ever needed, which I thankfully have now gotten rid of. 

I am actually glad I got rid of all the extra stuff I owned. Because while they were fun to have, the devices added barely any net value to my life. I just had them because I wanted them, I never for a moment thought what will I do with them and where do I use them without forcing it upon myself in any way.

Even after being aware of all these things I got excited about the new devices when I saw then during the event. Wanting all the devices again, knowing very well that I have absolutely no use for them. And I wasn't for even one moment convinced by any bullshit pandemic argument they were making for their devices during the session. I still wanted the new devices. Sure I know this is capitalism at play and my mental health doesn't help a lot, but why doesn't knowing about the triggers help change my interactions with them?

Another question I am asking myself is why did I even watch the whole event? I could have just viewed the 10 min highlights tomorrow or read about it much faster. And I knew how I would react to the entire event, but I still ended up watching and reacting to it in the most predictable way. Are these even valid questions or am I just going in circles? Did capitalism win even when I didn't make a purchase? Maybe I will have better answers or even questions before the next event.

**_TATA!_**

**_cube_**
