---
title: Pause and Play
author: TheDataAreClean
date: '2020-10-01'
slug: 2020-10-01-pause-play
categories:
  - writing
tags:
  - 100days
  - musings
description: 'Break.'
---

* __

**TL,DR** ; I am pulling the plug on writing for 100 days straight to focus on learning new things again.

If you have been reading this blog for the last few days, you might have noticed the quality has really plummeted. I have put across some absolute garbage that I wouldn't ever want to look at again. But more importantly, I realise the decision to stop is not the quality (which frankly was never that high to begin with) but the will to continue.

I have been sitting with the feeling for a few days, starting the blog every evening feeling extremely exhausted and half-heartedly putting something substandard across. More than anything I wanted to just be done with the blog for that day, just finish it again today, somehow reach 100 days and forget about the journey. Writing this blog again today is no different, and my attention is constantly wavering.

Another thing I realised that writing the blog meant giving up that time I could have used for other things. I was reading less, I was learning less, I more often than not started compromising on other aspirations to continue writing. All of this started making me annoyed, and the thing that I was so proud of was making me happy anymore.

I found myself going back to why I started writing this blog. I was not confident of my writing, I wanted to learn and I wanted to be comfortable sharing my work with anyone. I think I have achieved all of those goals fairly well, and I ended up writing for 60 days straight before I got tired of it. On top of all of that I am co-authoring a report with my colleagues and couldn't be more proud of my work.

I am at no point considering this as the last blog I will ever write, infact this is just the beginning. Writing is something I want to do professionally and this was just the first step towards that. Going forward, I plan to write 1-2 blogs every week with a little more research and thought put into it. Meanwhile, I want to clean up this blog a bit and make the repository open source. Some changes are long pending, so watch this space. Lastly, thank you for sticking around till Day 61, it has been an absolute pleasure. As always.

**_TATA!_**

**_cube_**
