---
title: Community Matters
author: TheDataAreClean
date: '2020-08-11'
slug: 2020-08-11-community-matters
categories:
  - community
tags:
  - 100days
  - development
  - leadership
description: 'Supreme Leader !'
---

* __

For a while I have been wondering what constitutes being a leader, how do you differentiate a good one from a bad one, how do you even evaluate their contributions? Do you lead by example or by guidance? If being a leader means giving everyone the space to have a voice, does it also mean checking with everyone if they have something to say? Does any of this even matter if the only thing that anyone looks at is the final output? After all, that's what capitalism cares about!

The questions becomes even trickier when you think about it in terms of a community. A bunch of individuals working towards a larger goal with their personal objectives in mind at the same time. It's not that different from a workplace in that regard, but they are neither getting paid nor obliged to collaborate. How do you bring a group like that together? Because even while working for a cause, the thing that matters in the end? Output.

I unfortunately don't have any answers, I am writing in the hope I will have better questions to ask myself at the end of this blog. 

I have always believed, leading by example is the only true way. You have to live up to the standards you are expecting from everyone. If you are not giving it your 100% then you shouldn't get to ask someone to do that. But what if your 100% comes at the harm of your own mental health and inadvertently others? Development sector is an unforgiving space and the burnout is very real. How do you sustain the level of commitment while also motivating others to do so.

To be honest, I am not a particularly good leader either myself. I don't always like being a leader too. I start with a grand plan, to include everyone, make everyone comfortable and enable them with whatever shit they need. But somewhere down the line some half baked effort which is not always intentionally bad will come along, and rather than supporting them to improve it I just lose trust and do it myself. Which is also a result of me stressing about something like that happening from day one. Yeah, not fun.

But I have worked with great leaders. They always support you but also know their boundaries, they will ensure everyone is empowered to contribute and collaborate. Because that's what a community needs most. Without that balance, without those boundaries everything feels like it's everyone's job. And since no one is responsible, no one really does anything. 

Maybe all of this is just subjective, maybe there are no good leaders? Maybe I felt those people were great leaders because I myself am a doer, I like to be there on-ground making things happen. Maybe it's just a system of responsibility and accountability well established that enables everyone to play their role better. If you design the ideal system, anyone with half decent skills is likely to succeed.

I don't want to believe that last bit, I don't think I believe it either. I just don't understand how it works. Maybe that's why I am not a leader, yet.

**_TATA!_**

**_cube_**