---
title: Saving Private Data
author: TheDataAreClean
date: '2020-08-07'
slug: 2020-08-07-saving-private-data
categories:
  - internet
tags:
  - 100days
  - privacy
description: 'Free will in the digital age..'
---

* __

# The Interwebs
So, I have been contemplating this thought for a while and I don't know where I stand on this. **What has been the collective impact of the internet on our world?** I know the status is ever changing, we have come through a lot of movements and I am also a fairly pessimistic person. But I still believe the collective good far outweighs the collective harm. And with all it's problems highlighted through the pandemic there is a lot that that internet was able to sustain just by being itself. At the same time who knows how long will that last, the world feels already up in shits. That's the pessimism kicking in, or maybe just realism.

# Also the Interwebs
I am also not trying to defend the internet or any of it's aspiring [gatekeepers](https://en.wikipedia.org/wiki/Big_Tech){target="_blank"}, I despise all of them as much as the next person. I am just aware of the default state of connectedness of our world now and how big a part these gatekeepers play in it. 

There are enough arguments floating around everyday, all valid, on the harms of the internet. From extremism to environment. One in particular I beleive is most critical, the collection of user data and weaponsing it against the same user of this internet.

# What is this behaviour
In a attempt to stay true to the principles of an open internet, the early "leaders" decided that a viable business model to sustain would be advertising. Enter, chaos. Early advertising was all cute and shit, but soon the entire ecosystem became and exercise in behaviour modification. Extracting more than enough information to ensure every last paisa is squeezed out of the users' pocket. And if it's not money, it's your attention and as a consequence your thoughts. Makes you wonder, how free are you using this "free" software.

# A compromise
A lot of the online discourse today feels like a compromise. See garbage, ignore garbage. The median value of the entire setup is decreasing at a ferocious speed. And if you want to fight this setup, you either need a lot of money or a lot of patience or both. Fighting this fight for as short as I have is tiring as fuck.

# Stone Age / New Age
I see two paths from here. First one; let's bring the whole shit down, no internet. Or the more realistic one, attaching a value to the service beyond the human cost. A cost that is not extracted without a users' will. A cost that is willing borne for the value deemed fair. Apparently when you pay, you almost always get a better experience. Surprise surprise.

**PS**. A lot of what I have written today has been inspired by [Jaron Lanier](https://en.wikipedia.org/wiki/Jaron_Lanier)'s work. I would strongly recommend you check it out. This one was really close to my heart, I hope you enjoyed reading it as much as I did putting it together. See you on the next one.

**_TATA!_**

**_cube_**